In [116]:
import pandas as pd
import typing
import subprocess
import os

In [117]:
def get_df(text: str) -> pd.DataFrame:
    def get_list_lines(text: str):
        def get_splitted_tab(line: str):
            return line.split('\t')

        def get_splitted_new_line(text: str):
            return text.split('\n')

        return list(map(lambda x: get_splitted_tab(x),
                        get_splitted_new_line(text)))

    def get_filtered(lines: list):
        return list(filter(lambda x: len(x) == 3, lines))
    
    return pd.DataFrame(get_filtered(get_list_lines(out_decoded)),
                        columns=['start', 'finish', 'tag'])

In [118]:
def exec_geniass(text: str) -> list:
    with open('geniass/data/tmp_in.txt', 'w') as f_in:
        f_in.write(text)

    p = subprocess.Popen(['./geniass', 'data/tmp_in.txt', 'data/tmp_out.txt'],
                         cwd='geniass/', stderr=subprocess.PIPE,
                         stdout=subprocess.PIPE)
    p.wait()
    out, err = p.communicate()

    with open('geniass/data/tmp_out.txt', 'r') as f_out:
        tmp_out = f_out.read()

    return tmp_out.split('\n')

def get_start_finish(text: str) -> pd.DataFrame:
    exec_geniass(text)
    
    p = subprocess.Popen(['ruby', 'sentence2standOff.rb', 'data/tmp_in.txt',
                          'data/tmp_out.txt', 'data/tmp_off.txt'], cwd='geniass/',
                         stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    p.wait()
    out, err = p.communicate()
    out_decoded = out.decode()
    
    return get_df(out_decoded)

In [119]:
get_start_finish('21826085	DPP6 as a candidate gene for neuroleptic-induced tardive dyskinesia.	We implemented a two-step approach to detect potential predictor gene variants for neuroleptic-induced tardive dyskinesia (TD) in schizophrenic subjects. First, we screened associations by using a genome-wide (Illumina HumanHapCNV370) SNP array in 61 Japanese schizophrenia patients with treatment-resistant TD and 61 Japanese schizophrenia patients without TD. Next, we performed a replication analysis in 36 treatment-resistant TD and 138 non-TD subjects. An association of an SNP in the DPP6 (dipeptidyl peptidase-like protein-6) gene, rs6977820, the most promising association identified by the screen, was significant in the replication sample (allelic P=0.008 in the replication sample, allelic P=4.6 Г— 10(-6), odds ratio 2.32 in the combined sample). The SNP is located in intron-1 of the DPP6 gene and the risk allele was associated with decreased DPP6 gene expression in the human postmortem prefrontal cortex. Chronic administration of haloperidol increased Dpp6 expression in mouse brains. DPP6 is an auxiliary subunit of Kv4 and regulates the properties of Kv4, which regulates the activity of dopaminergic neurons. The findings of this study indicate that an altered response of Kv4/DPP6 to long-term neuroleptic administration is involved in neuroleptic-induced TD.')

   start finish       tag
0      0    231  sentence
1    232    439  sentence
2    440    535  sentence
3    536    835  sentence
4    836    997  sentence
5    998   1078  sentence
6   1079   1205  sentence
7   1206   1357  sentence
8   1358   1524  sentence
9   1525   1766  sentence
10  1767   1951  sentence
11  1952   2222  sentence
12  2223   2347  sentence
13  2348   2383  sentence
14  2384   2673  sentence
15  2674   2851  sentence
16  2852   3178  sentence
17  3179   3311  sentence
18  3312   3473  sentence
19  3474   3709  sentence
20  3710   3832  sentence
21  3833   4116  sentence
22  4117   4268  sentence
23  4269   4525  sentence
24  4526   4680  sentence
25  4681   4751  sentence
26  4752   4905  sentence
27  4906   4972  sentence
28  4973   5109  sentence
29  5110   5201  sentence